name: Staging deployment

on:
  deployment:
  pull_request:
  #  types: [ closed ]

jobs:
  build:
    name: Deploy Staging
    runs-on: ubuntu-latest
    if: (github.event.pull_request.base.ref == 'master') || (github.event.deployment.environment == 'staging' && github.event_name == 'deployment')
    env:
      TEST: hej
    steps:
      - name: Check labels
        if: github.event_name == 'pull_request'
        run: |
          curl \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: text/json; charset=utf-8" \
            -H "Accept: application/vnd.github.flash-preview+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/64 | \
            jq -e 'any(.labels[]; .name == "deploy")'
      - name: Runrunrunr
        run: |
          echo "hejsan $TEST"
      - name: Set status
        if: always()
        run: |
            wget -O-- \
            --post-data "{\"state\":\"$(echo ${{ job.status }} | tr '[:upper:]' '[:lower:]')\", \"log_url\":\"https://github.com/${{ github.repository }}/actions\"}" \
            --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            --header "Content-Type: text/json; charset=utf-8" \
            --header "Accept: application/vnd.github.flash-preview+json" \
            https://api.github.com/repos/${{ github.repository }}/deployments/${{ github.event.deployment.id }}/statuses
